version: '3.3'

services:
  db:
    image: mysql:latest
#    image: mariadb:latest
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql-db2
    environment:
      #      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=blog
    ports:
      - "3306:3306"
  #    restart: always

  #service 2: definition of your spring-boot app
  customerservice:                        #it is just a name, which will be used only in this file.
    image: blog-service               #name of the image after dockerfile executes
    container_name: blog-service-app  #name of the container created from docker image
    build:
      context: .                          #docker file path (. means root directory)
      dockerfile: Dockerfile              #docker file name
    ports:
#      - "8084:8084"                       #docker containter port with your os port
      - "80:80"                       #docker containter port with your os port
#    restart: always

    depends_on:                           #define dependencies of this app
      - db                                #dependency name (which is defined with this name 'db' in this file earlier)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db2:3306/blog?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pwd

volumes:
  mysql-data:

#  sudo docker network create blog-net
#  sudo docker run -d --network blog-net --network-alias mysql -v mysql-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=pwd -e MYSQL_DATABASE=blog gyeongryun/mysql
#  sudo docker run -it --network blog-net nicolaka/netshoot
#  dig mysql
#  sudo docker run -dp 80:80 --network blog-net -e MYSQL_HOST=mysql -e SPRING_DATASOURCE_URL:jdbc:mysql://mysql-db2:3306/blog?createDatabaseIfNotExist=true -e SPRING_DATASOURCE_USERNAME:root -e SPRING_DATASOURCE_PASSWORD:pwd gyeongryun/blog-service
